---
- hosts: all
  become: yes
  pre_tasks:
    - name: Ansible Dir present
      file:
        path: /shathel-ansible
        state: directory
  tasks:
      - include: ../common/common.yml
      - include: ../common/gatherfacts.yml
      - include: ../common/firewall_private.yml
      - include: ../common/update-docker.yml